import React, { useState, useContext, useMemo } from 'react'
import { SocketContext } from '../../context/socketContext'
import MovieCard from './index'
import { AuthContext } from "../../context/authContext";
import { useHistory } from "react-router";

import "../../styles/textes.css";
import "../../styles/box.css";
import "../../styles/swipe.css";
import "../../styles/boutons.css";

const db = [
  { "netflixid": 60000861, "title": "American Psycho", "synopsis": "With chiseled good looks that belie his insanity, a businessman takes pathological pride in yuppie pursuits and indulges in sudden homicidal urges.", "img": "https://occ-0-1091-300.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABbq9EfVINBxAvmWTTbG9Py7E5-g149xKS8K1xSmV_pp03as0Y7kd_xwAExo7OzuDLSLL7oAkAx1mxBEA0ljfCWzxVA.jpg?r=6b9", "year": 2000, "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjIyMTYwMTI0N15BMl5BanBnXkFtZTgwNTU2NTYxMTE@._V1_SX300.jpg", "genre": "Comedy, Crime, Drama", "runtime": "101 min", "coutry": 7.6, "language": "English, Spanish, Cantonese", "plot": "Patrick Bateman is handsome, well educated and intelligent. He is twenty-seven and living his own American dream. He works by day on Wall Street, earning a fortune to complement the one he was born with. At night he descends into madness, as he experiments with fear and violence.", "country": "USA, Canada" },
  { "netflixid": 81176188, "title": "American Factory: A Conversation with the Obamas", "synopsis": "Barack and Michelle Obama talk with directors Steven Bognar and Julia Reichert about the documentary and the importance of storytelling.", "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABZs49cpx5DIw277wpTa9Qb4jRT5iGPZO9DRWlpDOwnasw_2n-OEoBYl9tn4MFkIOsI7JscYfdt-oifdZXzhUXnBUGtvsuUMqRx-4Qx7Vg-tLKEJxTb7ErDCcTzk.jpg?r=616", "year": 2019, "poster": "https://m.media-amazon.com/images/M/MV5BMmNjZWQzOTAtNGVhMC00ZTQ2LTllNmMtYmEyY2ZiM2MyMDQzXkEyXkFqcGdeQXVyMTcyMDgxNQ@@._V1_SX300.jpg", "genre": "Documentary, Short", "runtime": "10 min", "coutry": 5.3, "language": "English", "plot": "Barack and Michelle Obama talk with the directors of the documentary American Factory about the importance of storytelling and the impact of their film.", "country": "USA" },
  { "netflixid": 81001991, "title": "Altered Carbon: Resleeved", "synopsis": "On the planet Latimer, Takeshi Kovacs must protect a tattooist while investigating the death of a yakuza boss alongside a no-nonsense CTAC.", "img": "https://occ-0-2717-360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABaOiszaEqUNRI52EKBL3pI8KNrsyauXZqTC78IJX9rA05LI7bl-QbhB7J2pZ4eF7WQT40dfylLzfnmlMgjrpB55g-5sUa-WYw_yAvXMRiSCTNMiAl9Cg6L8wSI0.jpg?r=0ff", "year": 2020, "poster": "N/A", "genre": "Animation, Sci-Fi", "runtime": "N/A", "coutry": 0, "language": "N/A", "plot": "Anime series based on the sci-fi show &#39;Altered Carbon&#39;.", "country": "Japan" },
  { "netflixid": 80096984, "title": "Amateur", "synopsis": "After he&#39;s recruited to an elite prep school, a 14-year-old basketball phenom is confronted by corruption and greed in amateur sports.", "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABXknmi-2oNw7BWp743fdjXstp4Awhay9Onlbi-O7BCDc3AK742wfCXXbVXTVgq6-T1iPau7UHchLxI-C8npSstzn0DVdf6-FteOH09MbhzTkz0kPi6LGYXa8PiQ.jpg?r=248", "year": 2018, "poster": "N/A", "genre": "Drama, Sport", "runtime": "96 min", "coutry": 5.9, "language": "English", "plot": "A young basketball future star struggles with his personal life in pursuit of his dream.", "country": "USA" },
  { "netflixid": 81318026, "title": "Andhaghaaram", "synopsis": "As a blind librarian, dispirited cricketer and desolate psychiatrist each seek retribution and release, their lives overlap under eerie influences.", "img": "https://occ-0-1489-1490.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABWk4tEvVe-VvP68iqzsWikTZjnbd8yeHHWNOXqsAGhGZJiGn9_It-G8_mSGRz_aA9Jm_VX49qIiG6RzO1yzrhTaZhA.jpg?r=8d0", "year": 2020, "poster": "https://m.media-amazon.com/images/M/MV5BOWFmMzNkNTktYjMwOS00ODlkLWFhNTQtNmY3NWU1N2FjN2EzXkEyXkFqcGdeQXVyNDUyMTM4NTE@._V1_SX300.jpg", "genre": "Horror, Mystery, Thriller", "runtime": "N/A", "coutry": 0, "language": "Tamil", "plot": "A blind conjurer&#39;s struggle for survival, a washed-up cricketer&#39;s fight for deliverance and a desolate psychiatrist&#39;s quest for reclamation lead them to a labyrinth of obscurity while their...", "country": "India" },
  { "netflixid": 81090071, "title": "American Factory", "synopsis": "In this documentary, hopes soar when a Chinese company reopens a shuttered factory in Ohio. But a culture clash threatens to shatter an American dream.", "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABdHn8GRCfiWGb3iWqsG51WffPq_VpUy1u4wOh7AQL0EIz8fFZ9HqZNYixordKRiyn_QATGiSuhsvOmi9Vh-5bhmlH8vY_aIJd6vhvePy_YplwYiaZYg8zay3xF0.jpg?r=ff0", "year": 2019, "poster": "N/A", "genre": "Documentary", "runtime": "110 min", "coutry": 7.4, "language": "English, Mandarin", "plot": "In post-industrial Ohio, a Chinese billionaire opens a factory in an abandoned General Motors plant, hiring two thousand Americans. Early days of hope and optimism give way to setbacks as high-tech China clashes with working-class America.", "country": "USA" },
  { "netflixid": 70283197, "title": "Anchorman 2: The Legend Continues", "synopsis": "The &#39;70s are over, and the anachronistic Channel 4 news team tries to stay classy as they reassemble to join New York&#39;s first 24-hour news channel.", "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABUvVj92VUCLxNIWfza6G3vf1NZyK2NQi40dFXqPQSz-bOE0ApPaeRdhbW6Q5_FEi78c3b-4B5eWDKUXuht15YnmnPw.jpg?r=4d4", "year": 2013, "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjE5ODk0NjQzNV5BMl5BanBnXkFtZTgwODk4MDA1MDE@._V1_SX300.jpg", "genre": "Comedy", "runtime": "119 min", "coutry": 6.3, "language": "English", "plot": "Having left San Diego for New York City, Ron Burgundy is living the high life with his wife Veronica Corningstone and son Walter Burgundy. However, when the boss decides to promote Veronica to full time lead anchor and fire Ron, everything changes. Now heading back to San Diego, Ron is washed up and working part time at Sea World. His shot at redemption though comes in the form of a man named Freddie Schapp, who&#39;s an executive producer at the Global News Network, the world&#39;s first 24 hour round the clock news channel. He hires Ron, who proceeds to reunite the news team of Champ, Brick, and Brian, and head back to New York City. While there Ron and his news team are given the graveyard shift and a challenge. Ron comes up with a radical new idea to transform the news and that puts him at the top of the game once again. But how long will Ron&#39;s newfound fame last? And will Brick finally find true love?", "country": "USA" },
  { "netflixid": 80198596, "title": "Arctic Dogs", "synopsis": "When he stumbles upon evil Otto Von Walrus&#39;s scheme to melt the Arctic, ambitious delivery fox Swifty assembles a ragtag crew to protect the planet.", "img": "https://occ-0-2773-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABYjuYRN-YRz2Wm9TfRMPauBcgP0TCKwJD66B6mDGpu6T7z6BVZVyTgVHHs9Wjza_Z7qysOGol16nZ80oaPpaprgkKbtWOvLkh0awOO12QC8pF854YjjFvtPsvxY.jpg?r=47e", "year": 2019, "poster": "https://m.media-amazon.com/images/M/MV5BNTY1OTQyM2YtM2ZjOC00OWQwLTkzM2YtZjAyOGZkYjlhNWFhXkEyXkFqcGdeQXVyMTk5MzE1MTY@._V1_SX300.jpg", "genre": "Animation, Adventure, Comedy, Family", "runtime": "92 min", "coutry": 4.4, "language": "English, Korean", "plot": "Swifty the Arctic fox works in the mail room of the Arctic Blast Delivery Service but dreams of one day becoming a Top Dog (the Arctic&#39;s star husky couriers). To prove himself worthy of the Top Dog role, Swifty secretly commandeers one of the sleds and delivers a package to a mysterious location. He stumbles upon a secret fortress where he comes face to face with Otto Von Walrus, a blubbery evil genius who walks around on mechanical legs and commands a loyal army of oddly polite puffin henchmen. Swifty soon discovers Von Walrus&#39; plan to melt the polar ice caps and flood the world in order to reign supreme. Now, Swifty has to enlist the help of his friends: PB, a concerned polar bear, Lemmy, a scatterbrained albatross, Bertha and Leopold, two conspiracy theorist otters and Jade, a worldly fox. This ragtag group of Arctic misfits has to band together to stop Von Walrus&#39; sinister plans and save the day.", "country": "India, UK, China, Canada, Japan, South Korea, USA" },
  { "netflixid": 60021044, "title": "American Pie 2", "synopsis": "Jim, Oz, Kevin and Stifler are back -- and hornier than ever! After their first year of college, they reunite and rent a beach house for the summer.", "img": "https://occ-0-2773-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABd89oY7z9Yyl1RJ7TjjJeiSzdHerswDSLzBOEFww9hfbHWbb0gyVeLLzY00lMDu8axedZ_2rhE3Z1CHM_vPGaocw1w.jpg?r=8c8", "year": 2001, "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BOTEyYjhiMjYtNjU3YS00NmQ4LTlhNTEtYTczNWY3MGJmNzE2XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg", "genre": "Comedy", "runtime": "108 min", "coutry": 6.4, "language": "English", "plot": "The whole gang are back and as close as ever. They decide to get even closer by spending the summer together at a beach house. They decide to hold the biggest party ever to be seen, even if the preparation doesn&#39;t always go to plan. Especially when Stifler, Finch and Jim become more close to each other than they ever want to be and when Jim mistakes super glue for lubricant.", "country": "USA" },
  { "netflixid": 81281412, "title": "Anaamika", "synopsis": "As a woman scours Hyderabad for her missing husband, she becomes entangled in a conspiracy that suggests there’s more to the mystery than meets the eye.", "img": "https://occ-0-38-41.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABagKfGs_5l2e2q_az5x3oktk2t26S8oyhEd_L8VZLchH8utZcOZRvjMTvfRZgjk1KWCGD-Z0VUMJBKhgSV9MydrcWQ.jpg?r=334", "year": 2014, "poster": "https://m.media-amazon.com/images/M/MV5BMmEzNmYxYjktYTBjOC00MTJiLTk5Y2YtZDBmOGNkZjA1ZDMzXkEyXkFqcGdeQXVyMjY1MTI1MDQ@._V1_SX300.jpg", "genre": "Thriller", "runtime": "145 min", "coutry": 5.6, "language": "Tamil, Telugu", "plot": "A NRI Anamika (Nayanthara) comes to Hyderabad in search of her husband Ajay Sasthri (Harshavardhan Rane), who has gone missing. She lodges a police complaint in a station which is the nearest to the hotel where he was staying. A sympathetic cop (Vaibhav) tries to help her, while his superior cop who seems to know the truth is lusting after her. Meanwhile, she stirs the state administration with her resolve to find her missing husband, and is thwarted by a cunning state minister (Naresh) and the intelligence chief (Pasupathy). Does Anamika fulfill her mission?", "country": "India" },
  { "netflixid": 70254956, "title": "Andreaskorset", "synopsis": "When an accident leaves Andreas paralyzed, a handyman arrives to make his home more accessible and becomes intimately involved with Andreas&#39;s wife.", "img": "https://occ-0-318-41.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABbBW7Sfz6DuLlg4Zm8crciYlIbSsUCnBIQcu7BKiMWV7UmdQ6cL3ghhsPJslFwNImHGkNqZk3hJQ-Y6XUQq5o95HdA.jpg?r=fff", "year": 2004, "poster": null, "genre": null, "runtime": null, "coutry": null, "language": null, "plot": null, "country": null },
  { "netflixid": 81191856, "title": "Animal Crackers", "synopsis": "Enchanted animal crackers turn Owen into whatever shape he eats! But to save the family circus, he&#39;ll have to keep them out of his evil uncle&#39;s hands.", "img": "https://occ-0-1091-299.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABdQ3ObAShC0sMGrjMS0vG3G86Ci2fVoCXrv8HnSjEEU8lKBn4IznlyNlv2HBKH6CHMN5U1yIg0FKNB20JEOhEvhKenpW3xA_QbpMfHDK6EH4PE7ROp_pUpRZygk.jpg?r=87f", "year": 2020, "poster": "https://m.media-amazon.com/images/M/MV5BNWZhYzk5NTQtZmViYS00ZjZlLTk0M2MtNWI4NGY4MGJkNmZmXkEyXkFqcGdeQXVyNjUwMzI2NzU@._V1_SX300.jpg", "genre": "Comedy, Musical", "runtime": "97 min", "coutry": 7.5, "language": "English", "plot": "Captain Spaulding, the noted explorer, returns from Africa and attends a gala party held by Mrs. Rittenhouse. A painting displayed at that party is stolen, and the Marxes help recover it. Well, maybe &#39;help&#39; isn&#39;t quite the word I was looking for--this is the Marx Brothers, after all...", "country": "USA" },
  { "netflixid": 81382161, "title": "Annabell&#39;s Spectacularities", "synopsis": "A young girl and her grandmother embark on a colorful, musical adventure to break a storybook spell and help a long-lost wizard.", "img": "https://occ-0-4039-1500.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABUJuG6AJoMUnJk3JWjU9BG5u5QPBqD-29xD0BDTM1yO4dr-sI3hiLh5Xj9azSGW-I2EJdcv6luSmsNT250CHR6qXCw.jpg?r=198", "year": 2014, "poster": null, "genre": null, "runtime": null, "coutry": null, "language": null, "plot": null, "country": null },
  { "netflixid": 81020531, "title": "Ana e Vitória", "synopsis": "After meeting by chance, two young musicians with differing views on love and life record an album that drastically alters their lives.", "img": "https://occ-0-1091-300.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABbDQEip1DZ5-V9tjPIoGykN9_5DMthUgVMLZa-OTFGZoHr_Cpm2BN1GSYzQ6zR-hAPijxzVRggWG6FM5gKvB84NCWQ.jpg?r=202", "year": 2018, "poster": "https://m.media-amazon.com/images/M/MV5BNDZkNGZmNDEtNzZjZi00MDYyLWExMTQtNmYzZjhhOTc5NjJiXkEyXkFqcGdeQXVyMTkzODUwNzk@._V1_SX300.jpg", "genre": "Biography, Comedy, Music, Musical, Romance", "runtime": "115 min", "coutry": 6.6, "language": "Portuguese", "plot": "Two girls have a chance encounter and instantly befriend. While trying to find themselves, they decide to pursue music together.", "country": "Brazil" },
  { "netflixid": 70237091, "title": "Änglar, finns dom?", "synopsis": "After a good-natured bank janitor falls for an upper-class, engaged woman, he schemes to impress her by making a fortune through the stock market.", "img": "https://occ-0-2851-41.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABZSMLbXQGxGKfZCHAfVU1myl_3gEPXtkMG34Y7w0_xrwXI8uouFkt7iaVnrCN-W-WoO7395fmn81T4-tjc_EQ34iTw.jpg?r=b66", "year": 1961, "poster": null, "genre": null, "runtime": null, "coutry": null, "language": null, "plot": null, "country": null },
  { "netflixid": 80092885, "title": "ARQ", "synopsis": "Trapped in a lab and stuck in a time loop, a disoriented couple fends off masked raiders while harboring a new energy source that could save humanity.", "img": "https://occ-0-2717-360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABSkF7OcJPwd74XorFRK62SO9G7zRdPgMfMLk8F9YmZf3TtDnpbQW18uBuJ7mLoB0ZM8UTAMarWe84p1hd0Eu5pDMwKdeqHLcBSLf20fwsAW3mzVY853BHzMbdfg.jpg?r=970", "year": 2016, "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjAxODQ2MzkyMV5BMl5BanBnXkFtZTgwNjU3MTE5OTE@._V1_SX300.jpg", "genre": "Action, Sci-Fi, Thriller", "runtime": "88 min", "coutry": 6.4, "language": "English", "plot": "Trapped in a lab and stuck in a time loop, a disoriented couple fends off masked raiders while harboring a new energy source that could save humanity.", "country": "Canada, USA" },
  { "netflixid": 80113589, "title": "Amar", "synopsis": "Young Laura and Carlos experience the intensity and fragility of first love, as life realities gradually tarnish their idealized notions of romance.", "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABRngR48Ptc5j6OFMBlMCdISiypUUbPQzPEELcSupUO56PkegmFgZfea2xKLW3_IUErbc5V6PW38OYy8I5Lc2ruE6Tg.jpg?r=8c1", "year": 2017, "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BOTIxZDRmYTgtYzU3YS00MTgwLTg2MTktMTM1ODcyNWQzMjM3XkEyXkFqcGdeQXVyMzY2NTg0NTA@._V1_SX300.jpg", "genre": "Drama, Romance", "runtime": "105 min", "coutry": 5.3, "language": "Spanish", "plot": "Laura and Carlos love each other as if every day was the last, and perhaps that first love intensity is what will tear them apart a year later.", "country": "Spain" },
  { "netflixid": 80043049, "title": "Anthony Jeselnik: Thoughts and Prayers", "synopsis": "There&#39;s no subject too dark as the comedian skewers taboos and riffs on national tragedies before pulling back the curtain on his provocative style.", "img": "http://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABRynJN0bU0ydMYv8lI8H-cr4sNaKHXm4MCaXLIi_54FfanisFEHYgcztkqaziYiQYjFfCMsm11n1WKu79hI06pkbdZ9kgHEUtxgTj03PUTcA3GDwLUQ-iofQ-sU.jpg?r=751", "year": 2015, "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BYzA1ZGI0ZDYtYWVkNi00ZWY3LWE5MzUtZWIwZmI0NTRhNmJiXkEyXkFqcGdeQXVyMjI0MjUyNTc@._V1_SX300.jpg", "genre": "Documentary, Comedy", "runtime": "59 min", "coutry": 7.8, "language": "English", "plot": "Stand up comedian and former Late Night with Jimmy Fallon writer Anthony Jeselnik brings his dark humor and wit to San Francisco.", "country": "USA" },
  { "netflixid": 80063956, "title": "Alvin and the Chipmunks: The Road Chip", "synopsis": "Furry trio Alvin, Simon and Theodore are on a cross-country trip to stop their guardian Dave from proposing to his girlfriend in this comic sequel.", "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABWco1RhHNbkEEZsQEs8JUh8TUt8BQFSSodl3FVEYHSo1Qyb5KQXSyeQDuyM35Gqk1w-v04W0x0tBbZ_r3moRzadtOQ.jpg?r=f29", "year": 2015, "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTQ1NjQyNTkyOF5BMl5BanBnXkFtZTgwNzA3OTUyNzE@._V1_SX300.jpg", "genre": "Animation, Adventure, Comedy, Family, Fantasy, Music", "runtime": "92 min", "coutry": 5, "language": "English, Spanish", "plot": "The Chipmunks believe that Dave plans to propose to his new girlfriend in Miami.--and dump them. They have three days to get to him and save themselves not only from losing Dave but also from gaining a terrible stepbrother.", "country": "USA" },
  { "netflixid": 60000407, "title": "American Beauty", "synopsis": "While struggling to endure his tightly wound wife, an unfulfilling job and a surly teen, a man becomes obsessed with one of his daughter&#39;s friends.", "img": "https://occ-0-2773-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABXxNu5krA23_xsktehhX89Jgl7UQBrJOu3LvrR8kbLO4mq-ZGzFZq-PeUHpmFwcRywwj_iGq3IULqp4mKbxcuu9qsw.jpg?r=219", "year": 1999, "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjM4NTI5NzYyNV5BMl5BanBnXkFtZTgwNTkxNTYxMTE@._V1_SX300.jpg", "genre": "Drama", "runtime": "122 min", "coutry": 8.3, "language": "English", "plot": "After his death sometime in his forty-third year, suburbanite Lester Burnham tells of the last few weeks of his life, during which he had no idea of his imminent passing. He is a husband to real estate agent Carolyn Burnham and father to high school student Janie Burnham. Although Lester and Carolyn once loved each other, they now merely tolerate each other. Typical wallflower Janie too hates both her parents, the three who suffer individually in silence in their home life. Janie tries to steer clear of both her parents. Carolyn, relatively new to the real estate business, wants to create the persona of success to further her career, she aspiring to the professional life of Buddy Kane, the king of the real estate business in their neighborhood. Lester merely walks mindlessly through life, including at his job in advertising. His company is downsizing, and he, like all the other employees, has to justify his position to the newly hired efficiency expert to keep his job. Things change for Lester when he falls in love at first sight with Janie&#39;s more experienced classmate, Angela Hays. Both Janie and Angela can see Lester&#39;s sexual infatuation with Angela, who courts such attention from any man as a sign that she is model material, she having once appeared in Seventeen and it a career to which she aspires. Lester&#39;s infatuation with Angela gives him a reenergized view on life, where he openly doesn&#39;t care anymore what anyone thinks about what he does, anyone except Angela. This infatuation coincides with the Fittses moving in next door: homophobic disciplinarian US Marine Colonel Frank Fitts who rules the house with a military fist (that fist being both figurative and literal), his semi-comatose wife Barbara Fitts, and their bright and quietly subversive eighteen year old son Ricky Fitts, who openly abides by his father&#39;s rules while behind the scenes lives by his own quite different perspective. Much like Lester&#39;s infatuation, Ricky immediately becomes infatuated with Janie, he who considers girls like Angela as ordinary. The entry of Angela and the Fittses into the Burnhams&#39; lives ultimately leads to each of the players confronting what is truly in his or her heart.", "country": "USA" },
  { "netflixid": 80195964, "title": "Anon", "synopsis": "In a future where technology has rendered privacy obsolete, a detective investigates a serial assassin who has been deleted from all visual records.", "img": "https://occ-0-1490-1489.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAAAf2jGoP6we2BFXEFw609ETv88XeGaWQiGuuychAJnePmCCcXyetnaFrXt4xSXFhsWPhqavAdFnXpq4Da93Zn6mS64rOlNso1-YgZjCruCJ_Orytaua023iEV3go.jpg?r=26d", "year": 2018, "poster": "https://ia.media-imdb.com/images/M/MV5BMjE0MjIwMDE2MV5BMl5BanBnXkFtZTgwMzM5MDQzNTM@._V1_SX300.jpg", "genre": "Crime, Drama, Mystery, Sci-Fi, Thriller", "runtime": "100 min", "coutry": 6.1, "language": "English", "plot": "ANON is set in a near-future world where there is no privacy, ignorance or anonymity. Our private memories are recorded and crime almost ceases to exist. In trying to solve a series of unsolved murders, SAL FRIELAND (Owen) stumbles onto a young woman (Seyfried) who appears to have subverted the system and disappeared. She has no identity, no history and no record. Sal realizes it may not be the end of crime but the beginning. Known only as THE GIRL, Sal must find her before he becomes the next victim.", "country": "Germany, USA, Canada" },
  { "netflixid": 81004470, "title": "Animal World", "synopsis": "An unlucky, debt-ridden teen resorts to his math skills when he&#39;s forced into a deadly tournament of rock-paper-scissors run by a diabolical host.", "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABVTNelbZhAiA3MP1a9yBCLXy3xQsw8YaokReDYCTm0HtC9Zd_ytbyJcU5Ttnhyd3gxIhUiPKqOgTCYKwSGvIU2pBqw.jpg?r=606", "year": 2018, "poster": "https://m.media-amazon.com/images/M/MV5BMjEyMzY1NTE3OF5BMl5BanBnXkFtZTgwMzUzNDk2NTM@._V1_SX300.jpg", "genre": "Action, Fantasy, Sci-Fi, Thriller", "runtime": "132 min", "coutry": 6.5, "language": "Hindi, Mandarin, English, Italian, French, Arabic", "plot": "A man finds himself deep in debt and is coerced to board a ship that hosts a risky gambling party.", "country": "China" },
  { "netflixid": 81148672, "title": "Arsenio Hall: Smart and Classy", "synopsis": "In his first stand-up special, Arsenio Hall discusses getting older, the changing times and culture, social issues and even bothersome baby toes.", "img": "http://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABfkxv9HK6BBhFmUfLKbR7KEh-7_UhkVxVmK4jCMtgbueELAOUh-DJBXsT337fZ3_AFO-fgdRfy5xMOeWBGGk35Du3mYUmaovwrCJfFnUO5-NYyKT6NIOOeSxs7I.jpg?r=ca4", "year": 2019, "poster": "https://m.media-amazon.com/images/M/MV5BYmQyZmIzNjQtMTJmOC00OGExLTg1YjEtYWJkZGE3ZDAwZjQwXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg", "genre": "Comedy", "runtime": "63 min", "coutry": 5.9, "language": "English", "plot": "Arsenio Hall performs his first stand-up comedy special, filmed live in San Jose, California in April 2019.", "country": "USA" },
  { "netflixid": 81413985, "title": "Any Crybabies Around?", "synopsis": "An immature young father in Akita becomes an outcast in his community after a media incident. Two years later he returns to ineptly try to make amends.", "img": "https://occ-0-56-55.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABW9k2wThQyeYkve9dx34s7j6dHZjokMoE76e0p5ILpEQBVwOihRoR_GKNdnCg-8DPb7KQa18kaFmp5aMo56hk0uvMQ.jpg?r=cba", "year": 2020, "poster": "https://m.media-amazon.com/images/M/MV5BYTc1MmJiYzEtOTZkNC00YWYyLTlmZTktNjRlYWFjYzcxNTYyXkEyXkFqcGdeQXVyMTI0MjI0NTc0._V1_SX300.jpg", "genre": "Drama", "runtime": "106 min", "coutry": 5.6, "language": "Japanese", "plot": "A naked drunk man shows up on a national live TV in the middle of a sacred festival Namahage where men dressed in ogre-like costume visit homes to scare kids not to do bad things in the ...", "country": "Japan" },
  { "netflixid": 81238721, "title": "ariana grande: excuse me, i love you", "synopsis": "Ariana Grande takes the stage in London for her Sweetener World Tour and shares a behind-the-scenes look at her life in rehearsal and on the road.", "img": "https://occ-0-993-988.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABWJ0ia6wb-6zWMODwK_FwFvet_p0RvUF2ykrY6XPVwsxgovZLviafz2OhlGzkEMUMECvKAQpzWXq-Kvmh8ec-lSLhr7CjUeO_awBzHERAo4mfoswd9a7_VVfDPk.jpg?r=482", "year": 2020, "poster": "https://m.media-amazon.com/images/M/MV5BNDZhOGJhNDgtMzI4NS00ZTkzLWI3MjItZWU2MmQzOTU0N2QyXkEyXkFqcGdeQXVyNjEwNTM2Mzc@._V1_SX300.jpg", "genre": "Documentary, Music", "runtime": "N/A", "coutry": 0, "language": "English", "plot": "Ariana Grande takes the stage in London for her Sweetener World Tour and shares a behind-the-scenes look at her life in rehearsal and on the road.", "country": "USA" },
  { "netflixid": 80158661, "title": "Annabelle: Creation", "synopsis": "Years after their daughter&#39;s death, a dollmaker and his wife open their home to several orphans, who soon begin to fear one of his eerie creations.", "img": "https://occ-0-1091-300.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABeZRaQSWNZGbbjyNiGwLiWpa-62vQ8lN1ur_LOtkyaTNINRfrFRKmZmlZjshOBxdN99qWr7yDzza57EVmbuvis4w7w.jpg?r=3af", "year": 2017, "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjA1MzIwMjMxNF5BMl5BanBnXkFtZTgwMDQ3NTc2MjI@._V1_SX300.jpg", "genre": "Horror, Mystery, Thriller", "runtime": "109 min", "coutry": 6.5, "language": "English, Spanish", "plot": "Twelve years after the tragic death of their little girl, a doll-maker and his wife welcome a nun and several girls from a shuttered orphanage into their home, where they become the target of the doll-maker&#39;s possessed creation, Annabelle.", "country": "USA" },
  { "netflixid": 70053463, "title": "Arthur and the Invisibles", "synopsis": "Ten-year-old Arthur discovers a world of tiny people living in his backyard, a find that may hold the secret to saving his family home.", "img": "https://occ-0-1490-1489.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAAAeGremTeC2gWpZjE3WGWnFL1uHneQ_CUgdhrvoyqiWFv5LQQd_-TIjhWdNE7PuXf_og7YmXt7G0_gcnk9fY81Vd8VA.jpg?r=924", "year": 2006, "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BNDQ2ODQ1NTM5OF5BMl5BanBnXkFtZTcwNjQzNTA0MQ@@._V1_SX300.jpg", "genre": "Animation, Adventure, Family, Fantasy", "runtime": "94 min", "coutry": 6, "language": "English", "plot": "Arthur is a spirited ten-year old whose parents are away looking for work, whose eccentric grandfather has been missing for several years, and who lives with his grandmother in a country house that, in two days, will be repossessed, torn down, and turned into a block of flats unless Arthur&#39;s grandfather returns to sign some papers and pay off the family debt. Arthur discovers that the key to success lies in his own descent into the land of the Minimoys, creatures no larger than a tooth, whom his grandfather helped relocate to their garden. Somewhere among them is hidden a pile of rubies, too. Can Arthur be of stout heart and save the day? Romance beckons as well, and a villain lurks.", "country": "France" },
  { "netflixid": 70264633, "title": "Arthur 3: The War of the Two Worlds", "synopsis": "In the last chapter of the trilogy, a miniaturized Arthur must find a way to grow back to his normal size to stop the evil Maltazard once and for all.", "img": "https://occ-0-1926-41.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABZuNKVaffz_xFAy9sHmgVg5EF5cph2UtLI9YXwvld0nn1xazfXdsqT_859WqbmLYFD9ePbZyPk1G84BWOzAs6uerPA.jpg?r=3a2", "year": 2010, "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTk3MTY2OTQ4Ml5BMl5BanBnXkFtZTcwNTIwNDI1NA@@._V1_SX300.jpg", "genre": "Animation, Adventure, Family, Fantasy", "runtime": "101 min", "coutry": 5.5, "language": "English", "plot": "Maltazard, the Evil M, is now 7 feet tall and evolving among the humans, causing terror wherever he goes. His goal is simple: forming an army of giant henchmen and ruling over the universe. Meanwhile, Arthur is still a Minimoy, and thus in a state where he&#39;s unable to fend him off. With the help of Selenia and Betameche, he hatches a plan to regain his usual size: all they must do is infiltrate Arthur&#39;s house through the pipeworks, catch an electric train from his bedroom to his grandfather&#39;s study and find an elixir that will make him grow back to his human size. Sounds simple enough, if it weren&#39;t for Darkos, Maltazard&#39;s own son, hot on their tails.", "country": "France" },
  { "netflixid": 81065784, "title": "Are We Done Yet?", "synopsis": "When authorities arrest his young son, a taxi driver must convince the courts and rabid media that he&#39;s not the criminal they seek.", "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABfTnZ3HzBsenex-Z-tamQlzr3PMjv2j2SQPTtFATeHHTArNsc9pKNKbYnLkgxlw4P_ipG0YJPdYnimSeu4ugQs-D3g.jpg?r=37d", "year": 2018, "poster": "https://m.media-amazon.com/images/M/MV5BMTIwMDQyNjQzNl5BMl5BanBnXkFtZTcwMjEwODI0MQ@@._V1_SX300.jpg", "genre": "Comedy, Family, Fantasy", "runtime": "92 min", "coutry": 4.2, "language": "English", "plot": "Newlyweds Nick and Suzanne decide to move to the suburbs to provide a better life for their two kids. But their idea of a dream home is disturbed by a contractor with a bizarre approach to business.", "country": "Canada, USA" },
  { "netflixid": 70307997, "title": "Ankhon Dekhi", "synopsis": "After a dramatic incident, Raje Bauji, a man in his late fifties, decides that he will only believe what he sees with his eyes.", "img": "https://occ-0-784-778.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABX8slkmndhZUIjjP_X_TwXpgNN0a-va-qpp36CZjTmo6C2rO3WaFreHJW7iW6ctrZG3PNePDrNBOJon4931CS8Tq3wk8LtY.jpg?r=3a9", "year": 2014, "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTQ1ODMzOTA5MV5BMl5BanBnXkFtZTgwOTA2MTAzMjE@._V1_SX300.jpg", "genre": "Comedy, Drama", "runtime": "107 min", "coutry": 8, "language": "Hindi", "plot": "Raje Bauji (Sanjay Mishra) is a man in his late fifties, living out a dreary but eventful life in a small house in old Delhi- where he lives with his extended family. A random incident is going to change his life in a dramatic way- though he does not realize at the moment. Bauji&#39;s daughter has been seeing a boy of ill repute. When that fact is revealed to the family, after much deliberation they decide to do the obvious- lock up the girl and go beat the willful boy. It is a funny old journey of this man, this old fool- who is both Lear and the fool.", "country": "India" },
  { "netflixid": 80227677, "title": "Anthony Jeselnik: Fire in the Maternity Ward", "synopsis": "Forging his own comedic boundaries, Anthony Jeselnik revels in getting away with saying things others can&#39;t in this stand-up special shot in New York.", "img": "http://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABaTpWWQvKOLmiquIy6qnvRCamAa-W7UBZbKIJft7XYmh868phLz58kzZrmL5rznVLqydeSR-hTDIYEOBEf4LRmEBbKBm0zP2GZ2Rt4l5ETalYJ-qD_Zz8SytGCw.jpg?r=111", "year": 2019, "poster": "N/A", "genre": "Comedy", "runtime": "64 min", "coutry": 7.1, "language": "English", "plot": "Forging his own comedic boundaries, Anthony Jeselnik revels in getting away with saying things others can&#39;t in this stand-up special shot in New York.", "country": "USA" },
  { "netflixid": 60021758, "title": "Asoka", "synopsis": "This elaborate Bollywood epic dramatizes one man&#39;s transformation from a vengeful and cunning warrior into a legendary leader and teacher of Buddhism.", "img": "https://occ-0-2773-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABbkD7SXXIuqJU7a70uja1Ty0VUlMrxD-yOP9r2ByyFWkZqLesNsAtLX4F1qu6SqdV-9nLdemvMx0mytyVl13_nz8og.jpg?r=2fd", "year": 2001, "poster": "N/A", "genre": "Documentary", "runtime": "N/A", "coutry": 0, "language": "Spanish", "plot": "N/A", "country": "Spain" },
  { "netflixid": 81205737, "title": "Animals on the Loose: A You vs. Wild Movie", "synopsis": "When wild animals escape from a sanctuary, Bear Grylls — and you — must pursue them and secure their protective habitat. An interactive special.", "img": "https://occ-0-4039-1500.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABbaLLrpAlChNzD-Aoxs6-ZB1P5nwqa5rXKxkH1jElyKBJde2TRCyJsKrvNkPdabRL2myTue7MywRdcLF5oO_itsuD-gBZ2RjAV4KNh6u_0h1mwcO4JCM8qPf5s_0PkByHfb2nG2UhJRgRnBfcSebrkF6mfgGkn3x_9fG0XdFxFgPNBq1Zon2eu3X1E5ujBtWBxepzs7anY4NqippDS9vjSI.jpg?r=5fb", "year": 2021, "poster": null, "genre": null, "runtime": null, "coutry": null, "language": null, "plot": null, "country": null },
  { "netflixid": 80046779, "title": "Anjelah Johnson: Not Fancy", "synopsis": "Actress and comedian Anjelah Johnson showcases her hilarious impressions to riff on European Gypsies, Vietnamese manicurists, Mexican moms, and more.", "img": "http://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABb0Kf_y_jJUaDGZtujuDi9n99piMt5d4G65_jZU93Yb75HSA6TbttOgnzlmZnOPjM9A4BrRjh3QfKATdatmD4gis-Nn6HOE_SA4J6zwxQKwVNprKb4axiYaIC5E.jpg?r=4e0", "year": 2015, "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BODVkNDE4ZTQtNTcyMS00OTI4LWI4NjMtYmI2ZjVlNGMxZTNjXkEyXkFqcGdeQXVyMTQxMzY0ODY@._V1_SX300.jpg", "genre": "Documentary, Comedy", "runtime": "90 min", "coutry": 5.8, "language": "Spanish, English", "plot": "Angelah Johnson waxes about religion, married life, travel, and food among other topics in this new laugh out loud and family friendly stand up special taped live in California.", "country": "USA" },
  { "netflixid": 80146800, "title": "Army of One", "synopsis": "Armed with a samurai sword, middle-aged Coloradan Gary Faulkner sets out on his own to find Osama bin Laden, in this comedy based on a true story.", "img": "https://occ-0-114-116.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABaeD-AVZv0_fkz5_fZgiZc-Cgvt49wCEhuVDJwIGUqnQQ8pbxZfHd_PK4IGbsdu2WTQ46mNHXFGszpdADAh-dthW2w.jpg?r=20b", "year": 2016, "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BZWY4NzQwNWUtYzVkYS00YjIwLWJkYmEtYmU4MmE5ZjJmMjEzXkEyXkFqcGdeQXVyNTU2NDMyOTM@._V1_SX300.jpg", "genre": "Biography, Comedy", "runtime": "92 min", "coutry": 5.1, "language": "N/A", "plot": "Frustrated with the U.S. Government for its fruitless efforts to bring down Al-Qaeda&#39;s leader Osama Bin Laden, the eccentric middle-aged, part-time construction worker Gary Faulkner, after a personal visit by God himself, takes the decision to embark on an adventure in the badlands of Pakistan to get the job done. With the intention to bloodlessly capture and bring the infamous, yet, elusive leader to justice, Colorado&#39;s former handyman turned vigilante, will overlook his problems with diabetes and meticulously prepare for the long and perilous journey. Between reality and pre-dialysis hallucinations, armed only with a teleshop katana and a Stars and Stripes hang glider, this American samurai on a mission from God is determined to take matters into his own hands and succeed at any cost. Is he a hero or a crackpot?", "country": "USA" },
  { "netflixid": 81227923, "title": "Asphalt Burning", "synopsis": "When the brakes slam on his wedding, Roy accepts a challenge from a new foe to race for his runaway bride at the iconic Nürburgring track in Germany.", "img": "https://occ-0-867-41.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABanXLB2d6LoW7lRYjiJxibn5u50ats0PHkmmSYao65R6IBFtZfDd4ZXGRQ0BK87raYQlKypw0yVaWgFjMUWbaVb0E2xgcguTSEpzF7RQrxTDr-LPFZuo3NMz6nw.jpg?r=7bd", "year": 2020, "poster": "https://m.media-amazon.com/images/M/MV5BOTFkZWJlMzUtNTAwYS00NzE5LTgxNTQtN2RkYzBhYzY1ZDY0XkEyXkFqcGdeQXVyNTY3MTY3MzE@._V1_SX300.jpg", "genre": "Action, Comedy", "runtime": "100 min", "coutry": 5.9, "language": "Swedish, Norwegian, German, English", "plot": "The third installment of the Børning-franchise.", "country": "Norway" },
  { "netflixid": 80239629, "title": "Animas", "synopsis": "A teen&#39;s eerie visions become increasingly frequent and terrifying after her longtime friend gets a girlfriend and his abusive dad is strangely killed.", "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABR9Yu8josUfyU9xhCj3GKxhX1FIUwivj9-NBlFFkgdVXtNinzaNnr9_7XowSLDT8OaxF6cw8Fuz4B19mvBJNtuJFiOralBV-c2OYPzpl7Srj2-S4PNC1k1Hhz_I.jpg?r=870", "year": 2018, "poster": "https://m.media-amazon.com/images/M/MV5BMzdiMmQwM2ItMmFjMS00YTM1LWJhMDctNmJjMjFjNmJmNzNjXkEyXkFqcGdeQXVyMTE0NzkzMQ@@._V1_SX300.jpg", "genre": "Horror, Thriller", "runtime": "83 min", "coutry": 4.8, "language": "Spanish", "plot": "This time, horror comes fron the other side.", "country": "Spain, Belgium" },
  { "netflixid": 60001802, "title": "An Egyptian Story", "synopsis": "While undergoing heart surgery in London, Yehia reflects on his life as his heart chamber becomes a courtroom where he&#39;s tried for his mistakes.", "img": "https://occ-0-768-769.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABanEj3N0VvONO98vvBNRuc_4Ehhqi5k6P4SrYzC3C1GbtksRaDTBpDhFLxgl6paZSkimcCYTTuxcoBk-JOJgl1GatA.jpg?r=54f", "year": 1982, "poster": null, "genre": null, "runtime": null, "coutry": null, "language": null, "plot": null, "country": null },
  { "netflixid": 70254944, "title": "Anklaget", "synopsis": "Teenage Stine accuses her father of sexually abusing her. But Stine has a history of lying, and her mother questions the accusation.", "img": "https://occ-0-38-1501.1.nflxso.net/art/75f1e/8125c8fe7591722cd41fce1e7df2e465a4c75f1e.jpg", "year": 2005, "poster": "http://ia.media-imdb.com/images/M/MV5BMTIzODQ2ODg1Ml5BMl5BanBnXkFtZTcwMDEzMDgyMQ@@._V1_SX300.jpg", "genre": "Drama", "runtime": "103 min", "coutry": 7.1, "language": "Danish", "plot": "On the surface Henrik and Nina Christofferson are an ordinary family living happily. But they have a problem. Their daughter, Stine, a difficult 14 year old, has a habit of telling lies in class. When Stine accuses her father of sexual abuse, and is believed by seemingly eager social workers, their family is thrust into crisis. Could Henrik have done it? And when Stine prepares to return home, the ugly side of family life is exposed.", "country": "Denmark" },
  { "netflixid": 22037751, "title": "American Pie", "synopsis": "This smash-hit comedy follows four high school seniors as they strive for the most eagerly anticipated rite of adulthood: losing one&#39;s virginity.", "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABVCQB8Lb7sfDGHr8jy1BOOp1zh_r5KjhId5L_uztgh6p0USGb0isDp7lSCipq5jr3VCLqT5_O0OoRUi7aVG9vj20IA.jpg?r=5fe", "year": 1999, "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTg3ODY5ODI1NF5BMl5BanBnXkFtZTgwMTkxNTYxMTE@._V1_SX300.jpg", "genre": "Comedy", "runtime": "95 min", "coutry": 7, "language": "English", "plot": "Jim, Oz, Finch and Kevin are four friends who make a pact that before they graduate they will all lose their virginity. The hard job now is how to reach that goal by prom night. Whilst Oz begins singing to grab attention and Kevin tries to persuade his girlfriend, Finch tries any easy route of spreading rumors and Jim fails miserably. Whether it is being caught on top of a pie or on the Internet, Jim always ends up with his trusty sex advice from his father. Will they achieve their goal of getting laid by prom night? Or will they learn something much different?", "country": "USA" },
  { "netflixid": 81382134, "title": "Artificial Svensson", "synopsis": "After an inventor gets tangled up in a case of mistaken identity, he is accidentally enlisted in the military and drawn into unexpected romantic affairs.", "img": "https://occ-0-4039-1500.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABegRYhR9x1dKchPPw-CKc80uD6ZT4sjLxe8kjkpE2P4fGPwRqqFRgioh3A36Sz0uVqID82GB_7OBL4rAT6_ZW6636Q.jpg?r=e9e", "year": 1929, "poster": null, "genre": null, "runtime": null, "coutry": null, "language": null, "plot": null, "country": null },
  { "netflixid": 70231922, "title": "Argo", "synopsis": "In 1979, six Americans take shelter from Iranian militants in the Canadian embassy, prompting the CIA to concoct an elaborate plot to rescue them.", "img": "https://occ-0-1490-1489.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAAAfBQhJMplmFnwNMpMywfujTkrOBGNCltQqXM9nP8dINSP5NloaH8A8gvQUO6_7mplrTT2kAnH8tdIikNooq4D-AOng.jpg?r=e37", "year": 2012, "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTc3MjI0MjM0NF5BMl5BanBnXkFtZTcwMTYxMTQ1OA@@._V1_SX300.jpg", "genre": "Biography, Drama, Thriller", "runtime": "120 min", "coutry": 7.7, "language": "English, Persian, Arabic", "plot": "In 1979, the American embassy in Iran was invaded by Iranian revolutionaries and several Americans were taken hostage. However, six managed to escape to the official residence of the Canadian Ambassador and the CIA was ordered to get them out of the country. With few options, exfiltration expert Tony Mendez devised a daring plan: create a phony Canadian film project looking to shoot in Iran and smuggle the Americans out as its production crew. With the help of some trusted Hollywood contacts, Mendez created the ruse and proceeded to Iran as its associate producer. However, time was running out with the Iranian security forces closing in on the truth while both his charges and the White House had grave doubts about the operation themselves.", "country": "USA, UK" },
  { "netflixid": 70126736, "title": "Arthur and the Revenge of Maltazard", "synopsis": "In a sequel to Arthur and the Minimoys, Arthur helps Selenia reach Necropolis, a lost city ruled by Maltazard, whose evil minions are stalking them.", "img": "https://occ-0-1926-41.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABQxi1_RtrwzAHAQWcE4l1ZfeMF9x7H4TpKDRkW_pmm8IjWVYHk8AgOyoI6folmlU6xlELC1hZYfvGMdHhZxTRUIxFg.jpg?r=179", "year": 2009, "poster": "N/A", "genre": "Family", "runtime": "N/A", "coutry": 4.8, "language": "English", "plot": "N/A", "country": "France" },
  { "netflixid": 70250213, "title": "Asterix: The 12 Tasks", "synopsis": "Julius Caesar issues a challenge to the Gauls: If they can complete 12 tasks, the Roman Empire is theirs. If they fail, they must submit to Caesar.", "img": "https://occ-0-768-769.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABeaZAriAYIZKsx_z_aRSncHwdXAjSap3jGQXhXHgPw5CG0T7MwJjx6bHDPhs7aB28oTnFL4x2oawVt2bAVXSB9eCMA.jpg?r=998", "year": 1976, "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BODA4OTc3NzgwN15BMl5BanBnXkFtZTcwMjQ2NDEyMQ@@._V1_SX300.jpg", "genre": "Animation, Adventure, Comedy, Family, Fantasy", "runtime": "82 min", "coutry": 7.7, "language": "French, English", "plot": "When Julius Cesar fears, that he will probably never be able to defeat the gaulic village of Asterix and his friends, he has the idea of offering the Gauls a deal: if they are able to solve twelve tasks that he selected, he will hand over the Roman empire to them. If not, they have to submit.", "country": "France, UK" },
  { "netflixid": 80100170, "title": "Always Be My Maybe", "synopsis": "After being unexpectedly dumped by their respective lovers, a man and a woman have a chance meeting at a resort and embark on a unique relationship.", "img": "https://occ-0-979-38.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABQM5lx44Q-fLSNWmcSjAc_fOp0CvFWhs3fmdpRwuzhJWf3pJnjYaNT3iWIeHJIBIllW24TfMv5oTn5asH73aVOvj3RWSmcU.jpg?r=fd4", "year": 2016, "poster": "https://m.media-amazon.com/images/M/MV5BZThmMGVhZGQtOGZlZS00OGQ3LWJiYmItMjg5Mjc0NGEyZjFiXkEyXkFqcGdeQXVyNTI5NjIyMw@@._V1_SX300.jpg", "genre": "Romance", "runtime": "112 min", "coutry": 6.8, "language": "Filipino, Tagalog", "plot": "Jake del Mundo (Gerald Anderson) gets rejected by his long-time girlfriend when he proposed to marry him. Tin-Tin Paraiso (Arci Muñoz) ends her &#39;NO LABELS&#39; relationship with a guy when she learned that after 3 years of being non-committal to her, he finally started an official relationship with someone else. The two of them meet in a beach resort where their broken hearts draw them to each other. And one date after another, they learn about each other&#39;s views on love, commitment and relationships until they find themselves in a limbo. Will Jake muster the courage to finally DTR aka &#39;Define Their Relationship&#39;? Will Tin-Tin get past the no labels phase and finally make this new relationship official? In this day and age of much available options and fleeting relationships, how do we assure love&#39;s certainty? When did we ever stop choosing a Yes or No and start falling in love with a MAYBE?", "country": "Philippines" },
  { "netflixid": 81017092, "title": "Along with the Gods: The Last 49 Days", "synopsis": "While defending an unlikely soul, the afterlife Guardians investigate an elderly man who’s outstayed his time on Earth, and delve into their own past.", "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABQwVB-VUy2s81CdizGxk6-NgGzvh2txeFolpWgrs--n6negHRrAKcX2TWu2Ls_YdqPWJ4BtWEPuY1NPWobX6uXNDmQ.jpg?r=5c1", "year": 2018, "poster": "https://m.media-amazon.com/images/M/MV5BN2Y2ZDAxYzUtNjg4Yi00YmM2LWE2ZTEtMjgyZThjNjg3YjUyXkEyXkFqcGdeQXVyNDY5MTUyNjU@._V1_SX300.jpg", "genre": "Action, Drama, Fantasy", "runtime": "142 min", "coutry": 7.1, "language": "Korean", "plot": "In the afterlife, one guardian helps a man through his trials, while his two colleagues help a former guardian on earth.", "country": "South Korea" },
  { "netflixid": 81382140, "title": "As Seen On Tv", "synopsis": "The tangled love life of a popular TV talk show host becomes even more complicated when he publishes a controversial book that he didn&#39;t even write.", "img": "https://occ-0-4039-1500.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABWCWCS2uCA5KyyHQWwazJRrpqwCtlDwnPA9Q0fm7LoViZE91tWeZD4zcC3IDmg3LtM8bg867Jfqo3V6AwH_DJlsTSg.jpg?r=941", "year": 2001, "poster": "https://m.media-amazon.com/images/M/MV5BNzA0MTg5ODQxNF5BMl5BanBnXkFtZTcwNzA2Mjc3OQ@@._V1_SX300.jpg", "genre": "Short Comedy", "runtime": "30 min", "coutry": 8.6, "language": "English", "plot": "After some clients show concern over the lack of ethnic diversity on the writing staff Aimee pulls in a former pimp as Walsh Entertainment&#39;s new \"Urban\" writer.", "country": "USA" },
  { "netflixid": 80117799, "title": "Arrival", "synopsis": "A linguist charged with finding a way to communicate with aliens that have landed on Earth uncovers a connection with meaning for mankind and herself.", "img": "https://occ-0-2042-299.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABTHC7Glc-rGvcSxmqw__QfZ_zD6aVh1mNOBIzgmZK1QWPY88yFMvh50wT3Surwyoz8WKM0l2Te3UKI-kc8PMlcauQA.jpg?r=77b", "year": 2016, "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTExMzU0ODcxNDheQTJeQWpwZ15BbWU4MDE1OTI4MzAy._V1_SX300.jpg", "genre": "Drama, Mystery, Sci-Fi, Thriller", "runtime": "116 min", "coutry": 7.9, "language": "English, Russian, Mandarin", "plot": "Linguistics professor Louise Banks leads an elite team of investigators when gigantic spaceships touchdown in 12 locations around the world. As nations teeter on the verge of global war, Banks and her crew must race against time to find a way to communicate with the extraterrestrial visitors. Hoping to unravel the mystery, she takes a chance that could threaten her life and quite possibly all of mankind.", "country": "USA, Canada" },
  { "netflixid": 81337086, "title": "Ari Eldjárn: Pardon My Icelandic", "synopsis": "In this English-language special, Icelandic comedian Ari Eldjárn pokes fun at Nordic rivalries, Hollywood&#39;s take on Thor, the whims of toddlers and more.", "img": "https://occ-0-2774-2773.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABZDQILCjISxJVwtoH11a14EyaKW-9pulRHFWrXv47ka4L35BNuv3dRHhkqeqW8wNK180bhcUYXmvakiQuz0j-XdADo6ceQGRt5yjArldRuv6ugwdnaP5OjNzvgs.jpg?r=f23", "year": 2020, "poster": null, "genre": null, "runtime": null, "coutry": null, "language": null, "plot": null, "country": null },
  { "netflixid": 246062, "title": "Alphaville", "synopsis": "This sci-fi noir centers on a secret agent&#39;s mission to destroy a sentient computer that controls by destroying freedom of thought and individuality.", "img": "https://occ-0-784-778.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABQBDAziDV3LIk2zXEqIetsQ_el4V0jKLZ76jaYmlkuPxQQRh-zKPPrUrb780kf90bFRqWA4nJMR2IFFYukynT-8aDQ.jpg?r=30d", "year": 1965, "poster": "https://m.media-amazon.com/images/M/MV5BMzk2MTlkM2EtNzNhYi00Y2YxLWIwODktNGQ0NDM2ZTgwODJiXkEyXkFqcGdeQXVyNjI5NTk0MzE@._V1_SX300.jpg", "genre": "Drama, Mystery, Sci-Fi, Thriller", "runtime": "99 min", "coutry": 7.1, "language": "French, English", "plot": "Lemmy Caution, an American private-eye, arrives in Alphaville, a futuristic city on another planet. His very American character is at odds with the city&#39;s ruler, an evil scientist named Von Braun, who has outlawed love and self-expression.", "country": "France, Italy" },
  { "netflixid": 70295580, "title": "Asfaltenglene", "synopsis": "Three friends plan to do nothing all summer when one&#39;s big brother is arrested for drugs. Now it rests on the Asphalt Angels to prove his innocence.", "img": "http://occ-0-760-401.1.nflxso.net/art/3d6e8/f1829a112b46a5c72f3d9d3caf4623c5dc73d6e8.jpg", "year": 2010, "poster": "http://ia.media-imdb.com/images/M/MV5BMjAwNjMxNjQwOF5BMl5BanBnXkFtZTgwNjQ5MDkzMzE@._V1_SX300.jpg", "genre": "Adventure, Family", "runtime": "77 min", "coutry": 4.6, "language": "Norwegian", "plot": "It&#39;s vacation. 12-year-olds Maja, Rikke and Ohna have big ambitions to not lift a finger this summer, but then the police find drugs hidden in the restaurant. Saigon House is closed and Ohna&#39;s big brother gets arrested.The girls know that he is innocent but he won&#39;t get out of jail before the drug league is exposed. It&#39;s a case for the East End Angels...", "country": "Norway" },
  { "netflixid": 81334879, "title": "Alone/Together", "synopsis": "Eight years after their breakup, college sweethearts Christine and Raf reconnect at different points in their lives as feelings from the past resurface.", "img": "https://occ-0-2851-1432.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABYI4HLErXYTzOUz4eJheEpeRIKj8JT44LI2O30qRoOWmF2smGR9W5Yx-YyBAjDcccp7bDa2p6SxeP1dEhiOhf74tWw.jpg?r=adf", "year": 2019, "poster": "https://m.media-amazon.com/images/M/MV5BMmQ2NmZkODEtZGYzZS00NjdiLTgzZTYtYjVkNTc3MGE2MWNlXkEyXkFqcGdeQXVyNTI5NjIyMw@@._V1_SX300.jpg", "genre": "Drama, Romance", "runtime": "103 min", "coutry": 7, "language": "Filipino, Tagalog", "plot": "After meeting again at an awards ceremony, a former couple discover they still have a connection.", "country": "Philippines" },
  { "netflixid": 81411221, "title": "Anonymous Venetian", "synopsis": "A musician living with a terminal disease spends a day with his ex-wife ahead of a concert performance as feelings of romance and nostalgia arise.", "img": "https://occ-0-1299-1432.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABYa8WGAtnml1BblFYY-ZmR21ri589XmuQRpweRbfZqY4fFlweKMwc-OsCWbWFMYLfzXKn15ffOLwxsdZ2_1N1Hm_5Q.jpg?r=2b0", "year": 1970, "poster": "https://m.media-amazon.com/images/M/MV5BNTk5Yzg2NDItZDAwMS00YWM4LThkMzItNjc1NDYyYjBjYzM5XkEyXkFqcGdeQXVyMTQ3Njg3MQ@@._V1_SX300.jpg", "genre": "Drama Romance", "runtime": "91 min", "coutry": 7, "language": "Italian", "plot": "A Venetian musician at La Fenice theatre is affected by an incurable disease. By chance he meets his ex-wife who is now living with another man. She finally realizes that she is still in love with him.", "country": "Italy" },
  { "netflixid": 80131621, "title": "Anja and Viktor", "synopsis": "Viktor and Anja&#39;s young love faces severe strain when she relocates to the city and gets an upscale job working with her old boyfriend.", "img": "https://occ-0-1926-41.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABafEtWtDdeSfUvSEAmccezuy13kY63JZLadmUcqTCcR-henEnKdxGYD9ZLtyxAKqUhFy1CUYLBfU29BXzu9CzohwTw.jpg?r=1ad", "year": 2001, "poster": "http://ia.media-imdb.com/images/M/MV5BZjllZjNlODYtMDQ3MS00ZTEyLTk5YTAtZGE0NjJjNTFhNTAyXkEyXkFqcGdeQXVyNDM0OTkxMzI@._V1_SX300.jpg", "genre": "Comedy, Romance", "runtime": "90 min", "coutry": 5.2, "language": "Danish", "plot": "When Anja gets a full-time job after her graduation and moves into a city apartment with a friend, her highschool boyfriend Viktor is left behind and frustrated. He decides to do something about it and gets a janitor job with an apartment in the same building as Anja. Still, with his girlfriend working all day and her ex-boyfriend Peter in a nearby flat, everything is not quite right for Viktor. And it only gets worse.", "country": "Denmark" },
  { "netflixid": 81018635, "title": "Arlo the Alligator Boy", "synopsis": "To find the father he never knew, optimistic Arlo leaves his swampy Southern home for New York City, making friends along the way. A musical adventure.", "img": "https://occ-0-4039-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABYD-Zpvgu7moKDyZ2Bup7TInAvTUvUfgWnRSFWDS5qnaZtz3FPVBu8KEFk776WNOuNRV_2FKfk-jJIaR2An7I7HiSUcD0ZBljXjJWcdVxr8EC83Trn_FOzD3L-g.jpg?r=fff", "year": 2021, "poster": null, "genre": null, "runtime": null, "coutry": null, "language": null, "plot": null, "country": null },
  { "netflixid": 81382062, "title": "Angel", "synopsis": "Faded 1980s rock star Angel Holst devises a novel method of reviving her former career: She&#39;ll whip up a media frenzy by faking her own death.", "img": "https://occ-0-4039-1500.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABbP2vcosiUWm5I-T8Tukxc4JttaOn-CwxEujIn2P4yDqejQqrpmfQRr9WC9MAkeCA8L7kj-dsmnaddlwa81SigvPaQ.jpg?r=0f4", "year": 2008, "poster": "https://m.media-amazon.com/images/M/MV5BODU0M2NjZjgtZmQ1Zi00OWIyLTg1ODctMTg4Njg0MmE5YzU4XkEyXkFqcGdeQXVyNzA5NjUyNjM@._V1_SX300.jpg", "genre": "Action Drama Fantasy Thriller", "runtime": "44 min", "coutry": 7.9, "language": "English", "plot": "The vampire Angelus now known as Angel has a human soul but committed terrible crimes in the past. Seeking forgiveness and trying to redeem himself he moves from Sunnydale (and a relationship with Buffy Summers of \"Buffy the Vampire Slayer\") to Los Angeles where he helps the downtrodden by thwarting the supernatural creatures that prey on them.", "country": "USA" },
  { "netflixid": 80117445, "title": "Assassin&#39;s Creed", "synopsis": "In this adaptation of the critically acclaimed video game franchise, a man on death row is rescued from execution by a mysterious organization.", "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABeQRJhd3-WKhzYMqFELo51KyUM9vrJKNNaFp-K7nXY2_FM11dbIvRxZtJQKWJ-Z4PBWVdJmWp4rk0ms6r6yqUGdV9w.jpg?r=d7b", "year": 2016, "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BNzE1OTczNTc1OF5BMl5BanBnXkFtZTgwMzgyMDI3MDI@._V1_SX300.jpg", "genre": "Action, Adventure, Fantasy, Sci-Fi", "runtime": "115 min", "coutry": 5.7, "language": "English, Spanish, Arabic", "plot": "Through a revolutionary technology that unlocks his genetic memories, Callum Lynch (Michael Fassbender) experiences the adventures of his ancestor, Aguilar de Nerha, in 15th Century Spain. Callum discovers he is descended from a mysterious secret society, the Assassins, and amasses incredible knowledge and skills to take on the oppressive and powerful Templar organization in the present day.", "country": "USA, France, UK, Hong Kong, Taiwan, Malta" },
  { "netflixid": 80013775, "title": "Annabelle", "synopsis": "When a husband finds the perfect gift for his wife -- a beautiful and rare doll -- the joy the creepy object brings to her is short-lived.", "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABbc7xDoYkSkufm0YVaL06gRiSe5RtR9cef9QhUJ8v5g0wCceDt-SfI3NdcYQj5K6boVuRSe2ul-puBIPoSRSNVJB3g.jpg?r=074", "year": 2014, "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjM2MTYyMzk1OV5BMl5BanBnXkFtZTgwNDg2MjMyMjE@._V1_SX300.jpg", "genre": "Horror, Mystery, Thriller", "runtime": "99 min", "coutry": 5.4, "language": "English", "plot": "John Form has found the perfect gift for his expectant wife, Mia - a beautiful, rare vintage doll in a pure white wedding dress. But Mia&#39;s delight with Annabelle doesn&#39;t last long. On one horrific night, their home is invaded by members of a satanic cult, who violently attack the couple. Spilled blood and terror are not all they leave behind. The cultists have conjured an entity so malevolent that nothing they did will compare to the sinister conduit to the damned that is now... Annabelle.", "country": "USA" },
  { "netflixid": 70055855, "title": "Anthony Kaun Hai?", "synopsis": "A forger uses a fake identity in trying to retrieve stolen diamonds buried in a penitentiary, unaware a mob assassin is on the trail of his phony alias.", "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABeBp6GZvM7k4MAilLKY8u4D766Gnhf8leG_amSxrvXlZSDBP8bDWpgWKPtS3CvDX2MB0aJ1gu-Gn3xiwRdf4hHvfOw.jpg?r=7af", "year": 2006, "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BODMzYTlhMTEtODQ4MC00YmRlLWIzYWQtMDk0MzI2OTZlNDUxXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg", "genre": "Mystery, Thriller", "runtime": "127 min", "coutry": 5.4, "language": "Hindi", "plot": "Two men, an assassin and his victim is a small time crook and a question lies between the men is WHO IS ANTHONY?", "country": "India" },
  { "netflixid": 80202874, "title": "Always Be My Maybe", "synopsis": "Reunited after 15 years, famous chef Sasha and hometown musician Marcus feel the old sparks of attraction but struggle to adapt to each other&#39;s worlds.", "img": "https://occ-0-2717-360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABZZR6FGycwBBuphHzm_oqc6OcWfxUd22P72YwS7UPNAIPtCf95-H6hdRisf-OeFCDit8eY0D42qvDdg8vobeiv1Cgxq-NoSfdg97zIg7n2hNJWYzFjP9kuFApOM.jpg?r=42e", "year": 2019, "poster": "https://m.media-amazon.com/images/M/MV5BNWVhYTA1ZWYtZTlkNi00ZDNhLWIwNDMtYTBhMTU2MGY1N2RhXkEyXkFqcGdeQXVyNDg4NjY5OTQ@._V1_SX300.jpg", "genre": "Comedy, Romance", "runtime": "101 min", "coutry": 6.8, "language": "English", "plot": "Everyone assumed Sasha and Marcus would wind up together except for Sasha and Marcus. Reconnecting after 15 years, the two start to wonder - maybe?", "country": "USA" },
  { "netflixid": 81151926, "title": "Angela&#39;s Christmas Wish", "synopsis": "With her father working far away in Australia, a determined Angela makes a plan — and a heartfelt wish — to reunite her family in time for the holidays.", "img": "https://occ-0-2430-2433.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABer6-lx1wjMZjjHvCphCyQsKIEF7HVO_d9ulG_56YpLO13wo8Q392-2tqJkXSvREbs9v0XiFlYcCN8TiXC9YN7yksepS9E-BMzWHOtqkRZrHmAveACNAJruCwUg.jpg?r=8e9", "year": 2020, "poster": "https://m.media-amazon.com/images/M/MV5BNTJlZTgyYjEtN2Y4Mi00MDU4LTliNzAtZmU1N2Y3YmNhOWQwXkEyXkFqcGdeQXVyMjkyMDI4NTQ@._V1_SX300.jpg", "genre": "Drama", "runtime": "99 min", "coutry": 6.4, "language": "English", "plot": "The ten year-old Angela and her little sister Ellie move to an old house in the countryside with her parents Mae and Andrew. Their mother has mental illness and has just left an institution and her husband tries to keep the dysfunctional family together. Angela is an imaginative disturbed girl that might have inherited the illness of her mother and is obsessed by purification to get rid of her sins; and has visions of the fallen angel Lucifer and the Virgin Mary. She leads her little sister in her paranoia and uses a circle of toys and dolls to protect them against evil. They have a crazy neighbor that Angela believes is an angel and she asks the woman how to find the way to heaven. When Mae returns to the institution, Angela becomes uncontrollable in her quest to heaven.", "country": "USA" },
  { "netflixid": 80156683, "title": "Arctic Heart", "synopsis": "Madly in love with a brilliant scientist studying an immunizing protein produced by penguins, a timid med student offers her body to his research.", "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABfJzEVtAJQLRenQC1TjBKm3FMX7qm6YwrK1r9atBurbB5fAb5KlXVQlqp5vRZ8KFG5JHPsi3AsMx-LM4f5iIxo1pzg.jpg?r=928", "year": 2016, "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMzZhOWU5NDMtZTIyOS00MjAzLTlhNzEtNjk4MGRhMzZhZjUzXkEyXkFqcGdeQXVyNTU5NTk3MDA@._V1_SX300.jpg", "genre": "Comedy, Drama, Romance, Sci-Fi", "runtime": "81 min", "coutry": 5.2, "language": "French", "plot": "Silently and hopelessly in love with brilliant and egotistical Professor Quignard, the shy Christophine has been pursuing her PhD at his research lab for eight years. Now, the professor and his team are on the verge of making a discovery that will rock the world of science and medicine: the key to universal immunity through &#39;ppm&#39;, a miracle penguin protein. All they are missing is approval from the funding board to begin human testing. In a crazy gesture to finally get her beloved&#39;s attention, Christophine injects herself with the compound, thereby, becoming the first ever human test subject. Instantly, Christophine, whose name he didn&#39;t even know, becomes the center of Quignard&#39;s focus, as he and his ever-devoted lab rat secretly embark on one far-fetched experiment protocol after another. until it becomes clear that immunity could be triggered by... lovemaking!", "country": "France, Belgium" },
  { "netflixid": 80013871, "title": "American Sniper", "synopsis": "U.S. Navy SEAL marksman Chris Kyle racks up an unprecedented number of kills in Iraq, even as his home life starts to slip away from him.", "img": "https://occ-0-2717-360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABR9gTNmBeuYPTIlDQ7_8w2Rr8Rpyt8OgQbTCOkKgAyQ7j9q_wGxb0v6YYyxy8NOeRsWGwo3yqZcBFSVYKF5uBsDFtQ.jpg?r=f28", "year": 2014, "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTkxNzI3ODI4Nl5BMl5BanBnXkFtZTgwMjkwMjY4MjE@._V1_SX300.jpg", "genre": "Action, Biography, Drama, War", "runtime": "133 min", "coutry": 7.3, "language": "English, Arabic", "plot": "Chris Kyle was nothing more than a Texan man who dreamed of becoming a cowboy, but in his thirties he found out that maybe his life needed something different, something where he could express his real talent, something that could help America in its fight against terrorism. So he joined the SEALs in order to become a sniper. After marrying, Kyle and the other members of the team are called for their first tour of Iraq. Kyle&#39;s struggle isn&#39;t with his missions, but about his relationship with the reality of the war and, once returned at home, how he manages to handle it with his urban life, his wife and kids.", "country": "USA" },
  { "netflixid": 81155726, "title": "America, venim!", "synopsis": "With dreams of performing in America, a Romanian theater company arrives in New York, where they meet a local agent who promises them a major tour.", "img": "https://occ-0-1490-1489.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABTLd1n3b_g5ZPRq75uJxYEAUG5OIxhCsH41-twR3LMFSCt6YfGYElrgWpYoe6vINF9VAjg6kS4md2SOzqKnyKUXqbw.jpg?r=a99", "year": 2014, "poster": null, "genre": null, "runtime": null, "coutry": null, "language": null, "plot": null, "country": null },
  { "netflixid": 81342639, "title": "AndrÃ© & his olive tree", "synopsis": "As he prepares to close his restaurant, Michelin-starred Chef André Chiang embarks on a personal and emotional journey of reflection.", "img": "https://occ-0-4039-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABUlGAjykLnsnCvzymWiPb-kNzfI0LWWZioCEnh8_YT_QkPcZPydSZ59yWqwAHXkqZZ72RaXUxf0pXvrkN9t0n4BkrA.jpg?r=f0a", "year": 2020, "poster": "https://m.media-amazon.com/images/M/MV5BNDgxMDgwNTc3NV5BMl5BanBnXkFtZTcwNzQ1MzMzMQ@@._V1_SX300.jpg", "genre": "Comedy, Drama", "runtime": "137 min", "coutry": 5.3, "language": "Swedish, English", "plot": "Fanny and Zack is back, after she inherited Änglagård last year. Everytone looks forward to their new stay. Axel has told Fanny he is her father, but who else? Ivar also thinks he is her father. Be ready for expectations and confusions.", "country": "Sweden" },
  { "netflixid": 81035836, "title": "Antar: Son of Shadad", "synopsis": "Learning he is the grandson of a famous knight, a young man hilariously fights a rival gang to win over the most beautiful woman in the tribe.", "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABcz8fODgGeMc6Ph8GJV8xJj8W8-2-NtsX297OEKj-hEUsYvYUHfbbig8PXmWNj46w1rkvR4ashdsU22rQPgj6_VHvQ.jpg?r=d95", "year": 2017, "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMWRmOTI3MjItZGNkMS00YzFlLTgzM2MtYzAxM2YwMTUxZmI2XkEyXkFqcGdeQXVyNDkwNDQyMzQ@._V1_SX300.jpg", "genre": "Comedy", "runtime": "113 min", "coutry": 3.9, "language": "Arabic", "plot": "Antar Al Absy&#39;s grandson fights the lion of men, he tries to beat him with all the power he has, in order to win the heart of the most beautiful girl in the village.", "country": "Egypt" },
  { "netflixid": 1153328, "title": "Anaconda", "synopsis": "When a deranged snake hunter cons his way onto a film crew&#39;s boat to hunt a giant anaconda, the group soon finds they&#39;ve become the reptile&#39;s prey.", "img": "https://occ-0-2773-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABa45JYGe6oXWoslRInZPIoNrCJiSzZKF4Ng05eej9NEGsLFTOHWVayQWENhSKAFEN-0paEvEb9JBGbJ2OqAuj8QpAQ.jpg?r=bcb", "year": 1997, "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTMzMTU5NjcxNl5BMl5BanBnXkFtZTcwMzE2NDU2MQ@@._V1_SX300.jpg", "genre": "Action, Adventure, Horror, Thriller", "runtime": "89 min", "coutry": 4.8, "language": "English", "plot": "When a documentary crew traveling through the Amazon jungle, picks up a stranded man, they are unaware of the trouble that will occur. This stranger&#39;s hobby is to capture the giant Anaconda snake, and plans to continue targeting it on their boat, by any means necessary.", "country": "USA" },
  { "netflixid": 81049949, "title": "Antoine Griezmann: The Making of a Legend", "synopsis": "With heart and determination, Antoine Griezmann overcame his small stature to become one of the world’s top soccer players and a World Cup champion.", "img": "https://occ-0-2717-360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABRb4qxOnJV4vVe914Dy1Sc-bBCEhUw5Z-wtk-VWmuyUw2_tu-x2r6CkuXViMcVjuwjt8SMW4j1L9MxS9Wf76vN2LRWw2eJqPUgPFef6xtQ9MEZ7mD2q6P1dkDjQ.jpg?r=abc", "year": 2019, "poster": "https://m.media-amazon.com/images/M/MV5BMmYyMGE5NjItNmRkZS00MDI3LWE4ZGItYjQxZmZkMWVjMjdjXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg", "genre": "Documentary, Biography, Sport", "runtime": "60 min", "coutry": 6.5, "language": "N/A", "plot": "With heart and determination, Antoine Griezmann overcame his small stature to become one of the world&#39;s top soccer players and a World Cup champion.", "country": "N/A" },
  { "netflixid": 80158148, "title": "Apostle", "synopsis": "In 1905, a drifter on a dangerous mission to rescue his kidnapped sister tangles with a sinister religious cult on an isolated island.", "img": "https://occ-0-2717-360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABeEwuF9VO3hbDNntQ2h4uTxOoJLkGPgjqmN2l4K6wEjA1jEDLcthnJEOY5F1O93-HfOofp0SDmdvxpB5N-4IMP4p80kz0jbyjDYYtuoi0cSkMrrBsVP_6LcHKqc.jpg?r=134", "year": 2018, "poster": "https://m.media-amazon.com/images/M/MV5BMTY1NDk0NjI4MV5BMl5BanBnXkFtZTgwNjUyNzMwNjM@._V1_SX300.jpg", "genre": "Drama, Fantasy, Horror, Mystery, Thriller", "runtime": "130 min", "coutry": 6.3, "language": "English", "plot": "The year is 1905. Thomas Richardson travels to a remote island to rescue his sister after she&#39;s kidnapped by a mysterious religious cult demanding a ransom for her safe return. It soon becomes clear that the cult will regret the day it baited this man, as he digs deeper and deeper into the secrets and lies upon which the commune is built.", "country": "UK" },
  { "netflixid": 262866, "title": "Apollo 13", "synopsis": "Technical troubles scuttle the Apollo 13 mission in 1971, risking the lives of astronaut Jim Lovell and his crew in this chronicle of a true story.", "img": "https://occ-0-768-769.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABUePg44xB4dT2f_4ex0MG_jkIbeUsJMSIuGJ7zoRfj2c1-y4QXdek2KWDdwwDSozioO2AUChL0msXGihhks4bJmFhw.jpg?r=fb7", "year": 1995, "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BNjEzYjJmNzgtNDkwNy00MTQ4LTlmMWMtNzA4YjE2NjI0ZDg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg", "genre": "Adventure, Drama, History", "runtime": "140 min", "coutry": 7.6, "language": "English", "plot": "Based on the true story of the ill-fated 13th Apollo mission bound for the moon. Astronauts Lovell, Haise and Swigert were scheduled to fly Apollo 14, but are moved up to 13. It&#39;s 1970, and The US has already achieved their lunar landing goal, so there&#39;s little interest in this &#39;routine&#39; flight.. until that is, things go very wrong, and prospects of a safe return fade.", "country": "USA" },
  { "netflixid": 81270779, "title": "Anchor Baby", "synopsis": "A Nigerian couple living in the U.S. face agonizing fallout when they defy deportation orders with the hopes of giving their unborn child citizenship.", "img": "https://occ-0-2851-41.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABbwGiXBaY1fZE-lm4WaaHI45IigIOKDXF3GcxJlq6FOPR_E22hk3e4rp2ki6xiQ8ZOFsn1O2LTcgFK1lT430CCUq0w.jpg?r=074", "year": 2010, "poster": "https://m.media-amazon.com/images/M/MV5BMTM4MzI5OTI1N15BMl5BanBnXkFtZTcwNTE4NTE5NQ@@._V1_SX300.jpg", "genre": "Drama, Thriller", "runtime": "95 min", "coutry": 7.1, "language": "English", "plot": "Married illegal immigrant couple, Joyce (Omoni Oboli) and Paul Unanga (Sam Sarpong) have been ordered to be deported by the US immigration. They agree to leave; only after Joyce who is 5 months pregnant delivers her baby inside the US. This will guarantee automatic citizenship for their child. Later, Paul is caught and deported. Then, Joyce struggles on her own to accomplish their dream. Joyce, meets Susan Backley (Terri Oliver), a married freelance writer who offers to help her with free accommodation until her baby is born. Joyce accepts the offer. Now, with the help of Susan, Joyce sets out on the most daring journey of her life; to achieve the &#39;American Dream&#39; for her unborn child. She will try by any means necessary.", "country": "Canada, Nigeria" },
  { "netflixid": 81037077, "title": "Amy Schumer Growing", "synopsis": "Amy Schumer spills on her new marriage, personal growth, making a baby and her mom&#39;s misguided advice in a special that&#39;s both raunchy and sincere.", "img": "http://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABVx1Gjv7yCMUqNNCQGhcGHqKxsrbgO7K8TEsW61qr02rA996k0i8YJAAQ_1NhVFY2MheFOkrkGoTi2vEfCbZL56bBgqvHVD8Jvraduw3EzQNsLINQqhCqAVIixc.jpg?r=eb2", "year": 2019, "poster": "https://m.media-amazon.com/images/M/MV5BOTZjMGZiODgtMjNhMC00ODIwLTk2ZDItOTNhMDZmMmNlYThlXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_SX300.jpg", "genre": "Comedy", "runtime": "60 min", "coutry": 5.3, "language": "English", "plot": "Amy Schumer&#39;s live stand-up set performed in Chicago where she jokes about marriage, pregnancy and personal growth.", "country": "USA" },
  { "netflixid": 81024100, "title": "American Son", "synopsis": "Time passes and tension mounts in a Florida police station as an estranged interracial couple awaits news of their missing teenage son.", "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABdtFQ73sPWU8ofxEX9_SvFlmI3lHFVeOZ10cSn7vs7SNEyZPqz5g-DyX4Ulo0wncP5nnJ4nIjpALZt_XjIbrk6kXUAkvw-THOVYWJOEuQmfGWbYeushUp-GWsvI.jpg?r=e36", "year": 2019, "poster": "https://m.media-amazon.com/images/M/MV5BODliNWZkNmQtNzkwNi00ODY1LWIzYjQtZDNiYzM4MDc1NWNiXkEyXkFqcGdeQXVyNjgzMjQ0MTA@._V1_SX300.jpg", "genre": "Drama", "runtime": "90 min", "coutry": 5.6, "language": "English", "plot": "An estranged couple reunite in a Florida police station to help find their missing teenage son.", "country": "USA" },
  { "netflixid": 81035731, "title": "Aruna and Her Palate", "synopsis": "An epidemiologist turns her nationwide bird flu investigation into a chance to sample local delicacies en route, with three friends along for the ride.", "img": "https://occ-0-2717-360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABfhsEP75rTP8A7eh4tthoAg3iA5wI1PIbRPsv_CaYUCGDkUoBteH71P41TU9ZDQllLaliD9FdBy9zn0U3dVv6X3TkQ.jpg?r=85d", "year": 2018, "poster": "https://m.media-amazon.com/images/M/MV5BMTBhNDY5NTItMGNlNS00YWFkLTg3NDMtNDZkZTE0ZGExNzUzXkEyXkFqcGdeQXVyNzY4NDQzNTg@._V1_SX300.jpg", "genre": "Drama", "runtime": "106 min", "coutry": 7.6, "language": "Indonesian", "plot": "An epidemiologist tried to satisfy her obsession with food when she was assigned to investigate a bird flu case.", "country": "Indonesia" },
  { "netflixid": 81043345, "title": "Among Family", "synopsis": "Amid a marital crisis, Fikret befriends songstress Solmaz after a wacky encounter and must fill in as the father of her soon-to-wed daughter.", "img": "https://occ-0-2717-360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABdGP7-xmA6TUBV6Jx-NeyoxQUAgb46_6jsWtgQYvWlXu3CWjR0xprf4UV5YJBAgs3C5pA9eMTTg0aOPHBCVtRFthJg.jpg?r=d30", "year": 2017, "poster": "https://ia.media-imdb.com/images/M/MV5BNTYxMGI2NmItOGE0YS00YjM4LWExOGYtYjdhZjU0ZGFhNzdjXkEyXkFqcGdeQXVyODY1MDkwOQ@@._V1_SX300.jpg", "genre": "Comedy", "runtime": "124 min", "coutry": 7.8, "language": "Turkish", "plot": "Life of a singer, her daughter and her friends change when they meet with a divorced man.", "country": "Turkey" },
  { "netflixid": 81149214, "title": "Alt Love Building", "synopsis": "Nine couples attend a weekend retreat to mend their troubled relationships, only to find their counselors need more help than they do.", "img": "https://occ-0-3467-3466.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABUyV9UjSYJM8zkGAqV1k4gIf1JuviTHAJaTB8LnQgNg7lwdKRnznSsF7N9-89wFx7n28WtJQl323Vi4qca2vtnZGZA.jpg?r=94f", "year": 2014, "poster": "https://m.media-amazon.com/images/M/MV5BMzdlNmMxOTItZmI4MC00YjI4LTg1ZjYtODJiYzkzZDlkODg0XkEyXkFqcGdeQXVyNDgxMDU4NTU@._V1_SX300.jpg", "genre": "Comedy", "runtime": "", "coutry": 6, "language": "Romanian", "plot": "", "country": "Romania" },
  { "netflixid": 81311782, "title": "An Unremarkable Christmas", "synopsis": "An accountant and aspiring magician invites his boss to spend Christmas with his family â€” unaware that he&#39;s one of Colombia&#39;s most-wanted criminals.", "img": "https://occ-0-1081-1001.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABWo7km66xioQ4TE8cghpOx43MS-86N-XmlXwzaVyS_QjM6IwrdwWtFU9V91jc2DyrH18aNsG1PEHJw-hPUPAQ6X8uxPXexOlhn5eAFFZ3A5Ycf5acsgixh_E5GI.jpg?r=12b", "year": 2020, "poster": "https://m.media-amazon.com/images/M/MV5BYTNlOTFhNmMtYmZjNy00YjkyLWE0YjUtYzI5OGM4ZjQ1ZWY2XkEyXkFqcGdeQXVyODc0OTEyNDU@._V1_SX300.jpg", "genre": "Comedy, Drama", "runtime": "82 min", "coutry": 0, "language": "Spanish", "plot": "Before the events of S1, Juanquini, El Ñato and Captain González shared one Christmas wish: being courageous enough to change their lives. One mysterious character, El Dañado, could be the one who makes their dreams come true.", "country": "Colombia" },
  { "netflixid": 81346073, "title": "Andhakaaram", "synopsis": "As a blind librarian, dispirited cricketer and desolate psychiatrist each seek retribution and release, their lives overlap under eerie influences.", "img": "https://occ-0-1489-1490.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABV19DoqQwSE33tV0NRyTbiP3USvqfWHt119SkqmtRyfEbgANHBE_Mo4aJbDGBNw8UvP6t79O9vtYQkl3a41h3Xyi5Q.jpg?r=19e", "year": 2020, "poster": null, "genre": null, "runtime": null, "coutry": null, "language": null, "plot": null, "country": null },
  { "netflixid": 70139073, "title": "Arjun: The Warrior Prince", "synopsis": "This animated retelling of the classic Indian tale of Prince Arjun -- part of the Sanskrit epic Mahabharata -- begins during the prince&#39;s youth.", "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABZ6Fzh4X25iYgZj3psgU6GmyPI_F3vLu9n1W4kkpJDL5txydwxCWuUc-FRQiiseI3eMyRQ4EAElxN9sytMWZZr99Rw.jpg?r=fcc", "year": 2011, "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMzA5MTIxNjA5NV5BMl5BanBnXkFtZTcwNTExMDI4Nw@@._V1_SX300.jpg", "genre": "Animation, Action, Adventure", "runtime": "96 min", "coutry": 6.8, "language": "Hindi", "plot": "Legend knows him as an archer of unwavering focus, the soldier who fought a battle in his own heart before taking up arms against his enemy. This is the untold story of Arjun, hero of the Mahabharata. A precocious talent plunged from boyhood and innocence into a murky world of deceit and betrayal, coming of age to become the most powerful warrior of his time. From the dusty plains of Hastinapur to the icy peaks of the Himalayas, Arjun: The Warrior Prince is the story of a man discovering what it takes to be a hero.", "country": "India" },
  { "netflixid": 80214451, "title": "Along with the Gods: The Two Worlds", "synopsis": "A firefighter dies and arrives in the afterlife, where guardians shepherd him through seven trials and a perilous journey through different hells.", "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABQxaXluhZsAoIdXrJMEep422yrBgpbErjAexiYx8Y13jCF4jVzYFTOHxf8spNDTa64414IEPjL5YX6Iy_QOTU7WSHQ.jpg?r=fb2", "year": 2017, "poster": "https://m.media-amazon.com/images/M/MV5BN2FjN2Q0ZWQtN2NiOC00MTZjLTg3ZDEtMmVkNzM0ODBkYmU1XkEyXkFqcGdeQXVyNTUxNTI3MzY@._V1_SX300.jpg", "genre": "Action, Drama, Fantasy", "runtime": "139 min", "coutry": 7.3, "language": "Korean", "plot": "After a heroic death, a firefighter navigates the afterlife with the help of three guides.", "country": "South Korea" },
  { "netflixid": 81411153, "title": "Animals In The Great War", "synopsis": "This documentary examines the mules, dogs, pigeons and other animals who provided critical services — and comfort — to soldiers during World War I.", "img": "https://occ-0-4039-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABZLgCU3TA5cyK4u3FkIXyTwKc5DMIK13HiJz3bv0GqooxqAa7EXhMEkYm-93rVLGazDUot1SKOAAF1aCpkP1xwl22g.jpg?r=3fd", "year": 2015, "poster": null, "genre": null, "runtime": null, "coutry": null, "language": null, "plot": null, "country": null },
  { "netflixid": 80150002, "title": "Amy Schumer: The Leather Special", "synopsis": "Comic sensation Amy Schumer riffs on sex, dating and the absurdities of fame in a bold and uncensored stand-up set at Denver&#39;s Bellco Theater.", "img": "http://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABcY68ZGMPzRkm29rO7oyd2o4fptFuh0nnYSQX7sPyhG1Cx8jqFlqFzhlE8VGaYE8HRv-JYsIA3Vy4VaOkEdZniUhX25H42EHZlz50LRgfLC0JfFIEMXG28ZfgTg.jpg?r=6cb", "year": 2017, "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMGMxYWY1MTktZDFlNC00YjdjLTk5MGMtODEwNTZiY2MxZjk1XkEyXkFqcGdeQXVyNTI3NjIyMjI@._V1_SX300.jpg", "genre": "Comedy", "runtime": "57 min", "coutry": 2.9, "language": "English", "plot": "Three minutes in to her set, Amy Schumer claims that all good comedians have a &#39;leather special,&#39; where they wear all leather and regret it later in their careers--this is hers. Amy muses on love, life, dating, and womanhood in her first Netflix comedy special.", "country": "USA" },
  { "netflixid": 81281469, "title": "Ani... Dr. Kashinath Ghanekar", "synopsis": "From his singular career to his personal demons, this biopic chronicles the short yet prolific life of the Marathi dentist-turned-superstar.", "img": "https://occ-0-2851-1432.1.nflxso.net/dnm/api/v6/1lcgfy_NA26l7dfd356LqCUdNPM/AAAABd433JwKRehR234CKPzSQFvoJ28fCxvQKnP4BuVJIPx5kOy68ZpEqu6FKTpbEhoHIFxUDWplKprODDCh0nQOIk21AWHTVa6D1dTU3dJogk2sh8s.jpg?r=897", "year": 2018, "poster": "https://m.media-amazon.com/images/M/MV5BY2Q0ZGY0YzQtY2VmYy00NmQ3LWI4NWQtMjAyNGZjZmZmOTIwXkEyXkFqcGdeQXVyNTc1NTkzNTU@._V1_SX300.jpg", "genre": "Drama", "runtime": "159 min", "coutry": 8.7, "language": "Marathi", "plot": "This film is a biopic of Dr. Kashinath Ghanekar, legendary Marathi actor, journey to the peak of popularity, events that shaken his personal and professional life unto his unfortunate demise at early age.", "country": "India" },
  { "netflixid": 80190101, "title": "Anjaan", "synopsis": "Mild-mannered Krishna comes to Mumbai to search for his gang-leader brother, and quickly finds himself in way over his head.", "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABeEvg_kXhko9XTTLQm2uu7wVI4-2TGzbv42dglZC2EU1peqbSIZjeX62hkY2WmFuCp5cn1WpMfs8yBUWswcCAwr0MA.jpg?r=65e", "year": 2014, "poster": "https://m.media-amazon.com/images/M/MV5BZDBhN2JlY2UtNGQyMy00MDllLWExYjEtNWU3YTVkYmM0MzQ4XkEyXkFqcGdeQXVyODE0NjUxNzY@._V1_SX300.jpg", "genre": "Action, Thriller", "runtime": "166 min", "coutry": 4.9, "language": "Tamil, Telugu, Hindi", "plot": "Raju &#39;Bhai&#39; & Chandru head a thriving gang in Mumbai, taking on & decimating all those who oppose them. When the story of their success reaches the ears of the dreaded don, Imran Bhai, they face his inevitable wrath. It is now up to Krishna, the brother of Raju Bhai, to identify the culprits responsible for the fate suffered by the duo and exact revenge.", "country": "India" },
  { "netflixid": 80230507, "title": "Angela&#39;s Christmas", "synopsis": "A trip to church with her family on Christmas Eve gives young Angela an extraordinary idea. A heartwarming tale based on a story by Frank McCourt.", "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABXTkIzL5ekSERQzEm-iKRVwlNomJ10ywej89V1rdFcv-_lfQRfWLFVnrZWWS0p9gH70FQDaaruAa2PGkw8T3aio3nmwJoKvuaN3j9kdjSbo8TCzm_X5WNcfmKJE.jpg?r=bd7", "year": 2018, "poster": "https://m.media-amazon.com/images/M/MV5BMDRiY2Y0NDYtODViNi00NWQzLWE2M2YtNjc4N2U4NjkzZjQ1XkEyXkFqcGdeQXVyNDkwMTM0Ng@@._V1_SX300.jpg", "genre": "Animation, Short, Adventure, Family", "runtime": "30 min", "coutry": 7, "language": "English", "plot": "Set in Ireland in the 1910s, &#39;Angela&#39;s Christmas&#39; is a funny, heart-warming and poignant story about the power of family and the innocent desire of a child to ensure everyone is safe, warm and loved at Christmas time.", "country": "Ireland, Canada" },
  { "netflixid": 20258084, "title": "Andaz Apna Apna", "synopsis": "Two young men -- Prem and Amar -- are broke and have no concrete plans for the future when they discover that a stunning heiress lives nearby. Both Prem and Amar make it their mission to charm the young lady into marriage.", "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABa52zf7lpjKKqJSltopDVbycfSUQGmBEJIKKkbpev1SrlKj282B1L1vJp3WG4brPdFkmvj4QySeJ4TLBm5cfFV1Biw.jpg?r=b45", "year": 1994, "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BNWE2MjhjMmMtNzQyMS00MmI0LTlkOTUtZDVlZjFlNmZkNDgyL2ltYWdlXkEyXkFqcGdeQXVyNjQ2MjQ5NzM@._V1_SX300.jpg", "genre": "Comedy, Family, Romance", "runtime": "160 min", "coutry": 8.2, "language": "Hindi", "plot": "Amar and Prem are two rivals who belonging to middle-class families with no scope of future advancement. Both individually, without the knowledge of the other decide to take matters into their hands and find ways to get rich quickly. Chaos and acrimony result when both find each other at loggerheads when both arrive to win the hand of the daughter of multi-millionaire Ram Gopal Bajaj amidst considerable upheavals when Shyam, the twin brother of Ram, decides to do away with Ram and assume his identity and thus take over the estate of the Bajaj family.", "country": "India" },
  { "netflixid": 80165083, "title": "Ares", "synopsis": "A futuristic France tries to keep its people from despair and rebellion over crippling poverty by engaging them with a violent TV competition show.", "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABTidqebnS8uLMaov4HxwvowdTzCRBS4UWNzx9n6cpWaOMKMIYLZdu8PWZtxmXmXRJx6kmrF8aIOJ8ZN3UZejbpN8Ew.jpg?r=fe4", "year": 2016, "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjk2NzFhNGMtOTczZC00MjQ3LWJjZTYtZDBlYTMyNDRmOWQ4XkEyXkFqcGdeQXVyNjkzNzExNzc@._V1_SX300.jpg", "genre": "Drama, Sci-Fi, Thriller", "runtime": "80 min", "coutry": 6.2, "language": "French", "plot": "In a near future, the world order has changed. With its 10 millions of unemployed citizens, France has now become a poor country. Its people wavers between rebellion and resignation and find an outlet in the shape of TV broadcast ultra brutal fights in which the players are legally doped and unscrupulous.", "country": "France" },
  { "netflixid": 80081155, "title": "Amanda Knox", "synopsis": "She was twice convicted and acquitted of murder. Amanda Knox and the people closest to her case speak out in this illuminating documentary.", "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABaql81MpHO3Zes11VW5TxCGhPy9MewQ18BWxHMto9iP78zTkVrexoI9r6WmqEdrFrm8Dws99s4pwaaKK4AJxl5YXNNDTKg9AcjiR-6kLRr3w52_8UEO-kCfD1nA.jpg?r=199", "year": 2016, "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BNTY5NjE4MTQyNF5BMl5BanBnXkFtZTgwMzg1NjEwMDI@._V1_SX300.jpg", "genre": "Documentary, Crime", "runtime": "92 min", "coutry": 6.9, "language": "English, Italian", "plot": "American exchange student Amanda Knox is convicted and eventually acquitted for the 2007 death of another student in Italy.", "country": "Denmark, USA" },
  { "netflixid": 70060009, "title": "American Gangster", "synopsis": "Denzel Washington stars as true-life Harlem drug lord Frank Lucas and Russell Crowe plays the outcast NYPD cop charged with bringing him down.", "img": "https://occ-0-1490-1489.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABRWLzXt50_bEx3U9ukMk4kFRpbpda0QapUhTv89feHTGj6G-O9e7AxqEOw2T4dtWVbOgZow8I2WGBVHNm9NTp1NuCw.jpg?r=543", "year": 2007, "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTkyNzY5MDA5MV5BMl5BanBnXkFtZTcwMjg4MzI3MQ@@._V1_SX300.jpg", "genre": "Biography, Crime, Drama, Thriller", "runtime": "157 min", "coutry": 7.8, "language": "English, Thai, Spanish", "plot": "Following the death of his employer and mentor, Bumpy Johnson, Frank Lucas establishes himself as the number one importer of heroin in the Harlem district of Manhattan. He does so by buying heroin directly from the source in South East Asia and he comes up with a unique way of importing the drugs into the United States. As a result, his product is superior to what is currently available on the street and his prices are lower. His alliance with the New York Mafia ensures his position. It is also the story of a dedicated and honest policeman, Richie Roberts, who heads up a joint narcotics task force with the Federal government. Based on a true story.", "country": "USA, UK" },
]
const alreadyRemoved = []
let charactersState = db // This fixes issues with updating characters state forcing it to use the current state and not the state that was active when the card was created.

function Swipe() {
  const Movies = db
  const history = useHistory();
  const [MovieIndex, setMovieIndex] = useState(0);
  const [lastDirection, setLastDirection] = useState(null);
  const childRefs = useMemo(() => Array(db.length).fill(0).map(i => React.createRef()), [])
  const socketContext = useContext(SocketContext);
  const owner = "test"//socketContext.group.owner;
  const username = "test"//AuthContext.username;
  const userId = AuthContext.userId;
  const token = AuthContext.token;
  const groupId = socketContext.groudId;
  const socket = socketContext.socket;

  const swipeMovie = (avis) => {
    const filmId = Movies[MovieIndex].netflixid;
    /*socket.emit('swipe', 
    {
      auth: {
        id: userId,
        token: token,
        },
      groupId,
      filmId,
      avis
    })
*/
  }

  const interrompreSwipe = () => {
    /*socket.emit('printClassement', 
    {
      auth: {
        id: userId,
        token: token,
        }
    })
*/
  }

  const swiped = (direction, nameToDelete) => {
    console.log('removing: ' + nameToDelete);
    setLastDirection(direction);
    alreadyRemoved.push(nameToDelete);
    if (direction == "left") {
      swipeMovie("false")
    }
    else {
      swipeMovie("true")
    }
  }

  /*socket.on('group', (data) =>{
    alert(data.user)
    console.log(data)
  })*/

  const outOfFrame = (name) => {
    console.log(name + ' left the screen!')
  }

  const swipe = (dir) => {
    setMovieIndex(MovieIndex + 1);
    if (dir == "left") {
      swipeMovie("false")
    }
    else {
      swipeMovie("true")
    }
  }

  return (
    <div className="box-ecran swipe-color" >
        <hr></hr>

        <div className='cardContainer'>
          <div>
            <div className=' background-vide'><h3>{Movies[MovieIndex].title}, {Movies[MovieIndex].year} ({Movies[MovieIndex].runtime})</h3></div>
            <hr></hr>

            <MovieCard className='swipe' key={Movies[MovieIndex].title} onSwipe={(dir) => {
              setMovieIndex(MovieIndex + 1);
              swiped(dir, Movies[MovieIndex].name)
            }
            }
              onCardLeftScreen={() => outOfFrame(Movies[MovieIndex].title)}>
              <div style={{ backgroundImage: 'url(' + Movies[MovieIndex].img + ')' }} className='card'>
              </div>
            </MovieCard>
            <hr></hr>

            <div className='buttons bouton-swipe box-horizontal'>
              <div className="bouton-swipe-non-hover">
                <button className="bouton-swipe-non" onClick={() => swipe('left')}>non</button>
              </div>
              <hr></hr>
              <div className="bouton-swipe-oui-hover">
                <button className="bouton-swipe-oui" onClick={() => swipe('right')}>oui</button>
              </div>

            </div>
            <h4> {Movies[MovieIndex].genre}</h4>
            <div>{Movies[MovieIndex].synopsis}
            </div>
            {owner === username &&
        <div className="bouton-rouge-hover">
          <button
            className="bouton-rouge-rempli"
            onClick={() => 
            history.push("/"),
            interrompreSwipe()
            }>
            Interrompre le swipe</button>
        </div>}
          </div>

        </div>


    </div>
  )
}

export default Swipe
